Repository woosung-j/portfolio_date_place, pull requests merged in 2022-11, with the labels that each got.

#7 Create admin.css
  장우성.date/src/main/webapp/WEB-INF/res/admin.css
Labels: ✨ Feature

#17 Issue#8 회원가입
  doc/DB구현.sql
  장우성.date/pom.xml
  장우성.date/src/main/java/com/my/date/dao/UserDao.java
  장우성.date/src/main/java/com/my/date/dao/UserDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/UserMap.java
  장우성.date/src/main/java/com/my/date/domain/User.java
  장우성.date/src/main/java/com/my/date/service/UserService.java
  장우성.date/src/main/java/com/my/date/service/UserServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/UserController.java
  장우성.date/src/main/resources/com/my/date/dao/map/userMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/main.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/login.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/mypage.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/signUp.jsp
Labels: ✨ Feature

#19 Fix. 로그인
  장우성.date/src/main/webapp/WEB-INF/view/user/login.jsp
Labels: 🐛 BugFix

#23 관리자 신고 조회 및 처리
  장우성.date/src/main/java/com/my/date/dao/DeclarationDao.java
  장우성.date/src/main/java/com/my/date/dao/DeclarationDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/DeclarationMap.java
  장우성.date/src/main/java/com/my/date/domain/Declaration.java
  장우성.date/src/main/java/com/my/date/domain/Detail.java
  장우성.date/src/main/java/com/my/date/domain/Place.java
  장우성.date/src/main/java/com/my/date/service/DeclarationService.java
  장우성.date/src/main/java/com/my/date/service/DeclarationServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/declarationMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/declaration/declareList.jsp
Labels: ✨ Feature

#25 DeclarationMap Refactoring
  장우성.date/src/main/java/com/my/date/domain/Declaration.java
  장우성.date/src/main/java/com/my/date/domain/DeclarationAdminDto.java
  장우성.date/src/main/resources/com/my/date/dao/map/declarationMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/declaration/declareList.jsp
Labels: 🔨 Refactor

#28 아이디 찾기 구현 완료 User#2
  장우성.date/pom.xml
  장우성.date/src/main/java/com/my/date/AppConfig.java
  장우성.date/src/main/java/com/my/date/dao/UserDao.java
  장우성.date/src/main/java/com/my/date/dao/UserDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/UserMap.java
  장우성.date/src/main/java/com/my/date/service/UserService.java
  장우성.date/src/main/java/com/my/date/service/UserServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/UserController.java
  장우성.date/src/main/resources/com/my/date/dao/map/userMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/main.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/findId.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/findIdResult.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/login.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/mypage.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/signUp.jsp
Labels: ✨ Feature

#32 admin 메뉴조회
  장우성.date/src/main/java/com/my/date/dao/MenuDao.java
  장우성.date/src/main/java/com/my/date/dao/MenuDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/MenuMap.java
  장우성.date/src/main/java/com/my/date/domain/Menu.java
  장우성.date/src/main/java/com/my/date/service/MenuService.java
  장우성.date/src/main/java/com/my/date/service/MenuServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/menuMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/menu/patchmenu.jsp
Labels: ✨ Feature

#33 나의 신고 + 신고내용 삭제
  장우성.date/src/main/java/com/my/date/dao/DeclarationDao.java
  장우성.date/src/main/java/com/my/date/dao/DeclarationDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/DeclarationMap.java
  장우성.date/src/main/java/com/my/date/domain/MyDeclarationDto.java
  장우성.date/src/main/java/com/my/date/service/DeclarationService.java
  장우성.date/src/main/java/com/my/date/service/DeclarationServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/DeclarationController.java
  장우성.date/src/main/resources/com/my/date/dao/map/declarationMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/declaration/myDeclare.jsp
Labels: ✨ Feature

#35 관리자 신고조회 Refactoring
  장우성.date/src/main/java/com/my/date/domain/DeclarationAdminDto.java
  장우성.date/src/main/resources/com/my/date/dao/map/declarationMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/declaration/declareList.jsp
Labels: 🔨 Refactor

#39 Fix. import
  장우성.date/src/main/java/com/my/date/dao/MenuDao.java
  장우성.date/src/main/java/com/my/date/dao/MenuDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/MenuMap.java
  장우성.date/src/main/java/com/my/date/service/MenuService.java
  장우성.date/src/main/java/com/my/date/service/MenuServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
Labels: 🐛 BugFix

#40 리뷰조회기능
  장우성.date/pom.xml
  장우성.date/src/main/java/com/my/date/dao/ReviewDao.java
  장우성.date/src/main/java/com/my/date/dao/ReviewDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/ReviewMap.java
  장우성.date/src/main/java/com/my/date/domain/Review.java
  장우성.date/src/main/java/com/my/date/domain/ReviewDto.java
  장우성.date/src/main/java/com/my/date/domain/ReviewImage.java
  장우성.date/src/main/java/com/my/date/domain/User.java
  장우성.date/src/main/java/com/my/date/service/ReviewService.java
  장우성.date/src/main/java/com/my/date/service/ReviewServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/ReviewController.java
  장우성.date/src/main/resources/com/my/date/dao/map/reviewMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/review/list.jsp
Labels: ✨ Feature

#45 feedList
  장우성.date/src/main/java/com/my/date/dao/FeedDao.java
  장우성.date/src/main/java/com/my/date/dao/FeedDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/FeedMap.java
  장우성.date/src/main/java/com/my/date/domain/Feed.java
  장우성.date/src/main/java/com/my/date/domain/FeedDto.java
  장우성.date/src/main/java/com/my/date/domain/Hashtag.java
  장우성.date/src/main/java/com/my/date/service/FeedService.java
  장우성.date/src/main/java/com/my/date/service/FeedServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/FeedController.java
  장우성.date/src/main/resources/com/my/date/dao/map/feedMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/community/listFeed.jsp
Labels: ✨ Feature

#44 Detail 리스트 조회
  장우성.date/src/main/java/com/my/date/dao/DetailDao.java
  장우성.date/src/main/java/com/my/date/dao/DetailDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/DetailMap.java
  장우성.date/src/main/java/com/my/date/domain/Detail.java
  장우성.date/src/main/java/com/my/date/service/DetailService.java
  장우성.date/src/main/java/com/my/date/service/DetailServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/detailMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/detail/patchdetail.jsp
Labels: ✨ Feature

#50 회원가입 메일 인증
  장우성.date/pom.xml
  장우성.date/src/main/java/com/my/date/MailConfig.java
  장우성.date/src/main/java/com/my/date/dao/UserDao.java
  장우성.date/src/main/java/com/my/date/dao/UserDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/UserMap.java
  장우성.date/src/main/java/com/my/date/service/MailSendService.java
  장우성.date/src/main/java/com/my/date/service/UserService.java
  장우성.date/src/main/java/com/my/date/service/UserServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/UserController.java
  장우성.date/src/main/resources/com/my/date/dao/map/userMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/main.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/login.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/signUp.jsp
Labels: 🐛 BugFix, ✨ Feature

#52 나의 신고 조회
  장우성.date/src/main/java/com/my/date/web/DeclarationController.java
  장우성.date/src/main/webapp/WEB-INF/view/declaration/myDeclare.jsp
Labels: 🐛 BugFix

#54 리뷰 추가 기능 구현
  장우성.date/src/main/java/com/my/date/dao/ReviewDao.java
  장우성.date/src/main/java/com/my/date/dao/ReviewDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/ReviewMap.java
  장우성.date/src/main/java/com/my/date/service/ReviewService.java
  장우성.date/src/main/java/com/my/date/service/ReviewServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/ReviewController.java
  장우성.date/src/main/resources/com/my/date/dao/map/reviewMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/review/add.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/list.jsp
Labels: ✨ Feature

#55 로그인 수정
  장우성.date/src/main/java/com/my/date/dao/UserDao.java
  장우성.date/src/main/java/com/my/date/dao/UserDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/UserMap.java
  장우성.date/src/main/java/com/my/date/service/UserServiceImpl.java
  장우성.date/src/main/resources/com/my/date/dao/map/userMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/user/login.jsp
Labels: 🐛 BugFix

#58 issue#41
  장우성.date/src/main/java/com/my/date/dao/UserDao.java
  장우성.date/src/main/java/com/my/date/dao/UserDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/UserMap.java
  장우성.date/src/main/java/com/my/date/service/UserService.java
  장우성.date/src/main/java/com/my/date/service/UserServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/UserController.java
  장우성.date/src/main/resources/com/my/date/dao/map/userMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/user/fixUser.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/removeUser.jsp
Labels: ✨ Feature

#60 issue#31
  장우성.date/src/main/java/com/my/date/dao/MenuDao.java
  장우성.date/src/main/java/com/my/date/dao/MenuDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/MenuMap.java
  장우성.date/src/main/java/com/my/date/service/MenuService.java
  장우성.date/src/main/java/com/my/date/service/MenuServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/menuMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/menu/patchmenu.jsp
Labels: ✨ Feature

#64 Fix. redirect 추가
  장우성.date/src/main/java/com/my/date/web/AdminController.java
Labels: 🐛 BugFix

#67 관심 지역 조회
  장우성.date/src/main/java/com/my/date/dao/RegionDao.java
  장우성.date/src/main/java/com/my/date/dao/RegionDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/RegionMap.java
  장우성.date/src/main/java/com/my/date/domain/Region.java
  장우성.date/src/main/java/com/my/date/domain/RegionDto.java
  장우성.date/src/main/java/com/my/date/service/RegionService.java
  장우성.date/src/main/java/com/my/date/service/RegionServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/RegionController.java
  장우성.date/src/main/resources/com/my/date/dao/map/regionMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/main.jsp
  장우성.date/src/main/webapp/WEB-INF/view/region/myRegion.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/mypage.jsp
Labels: ✨ Feature

#69 URL 수정
  장우성.date/src/main/webapp/WEB-INF/view/admin/declaration/declareList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/detail/patchdetail.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/main.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/menu/patchmenu.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/mypage.jsp
Labels: 🐛 BugFix

#70 admin 리뷰 조회
  장우성.date/src/main/java/com/my/date/dao/ReviewDao.java
  장우성.date/src/main/java/com/my/date/dao/ReviewDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/ReviewMap.java
  장우성.date/src/main/java/com/my/date/service/ReviewService.java
  장우성.date/src/main/java/com/my/date/service/ReviewServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/reviewMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/review/reviewList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/add.jsp
Labels: ✨ Feature

#73 Fix. place, AdminController, FileName
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/webapp/WEB-INF/view/admin/detail/patchDetail.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/menu/patchMenu.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/placeList.jsp
Labels: 🐛 BugFix

#74 issue#62
  장우성.date/src/main/java/com/my/date/dao/MenuDao.java
  장우성.date/src/main/java/com/my/date/dao/MenuDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/MenuMap.java
  장우성.date/src/main/java/com/my/date/service/MenuService.java
  장우성.date/src/main/java/com/my/date/service/MenuServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/menuMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/menu/patchMenu.jsp
Labels: ✨ Feature

#84 장소 조회
  장우성.date/src/main/java/com/my/date/dao/CommentDao.java
  장우성.date/src/main/java/com/my/date/dao/CommentDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/PlaceDao.java
  장우성.date/src/main/java/com/my/date/dao/PlaceDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/ReviewDao.java
  장우성.date/src/main/java/com/my/date/dao/ReviewDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/CommentMap.java
  장우성.date/src/main/java/com/my/date/dao/map/PlaceMap.java
  장우성.date/src/main/java/com/my/date/dao/map/ReviewMap.java
  장우성.date/src/main/java/com/my/date/domain/Detail.java
  장우성.date/src/main/java/com/my/date/domain/Place.java
  장우성.date/src/main/java/com/my/date/domain/PlaceDetailDto.java
  장우성.date/src/main/java/com/my/date/domain/PlaceImage.java
  장우성.date/src/main/java/com/my/date/domain/ReviewDto.java
  장우성.date/src/main/java/com/my/date/service/CommentService.java
  장우성.date/src/main/java/com/my/date/service/CommentServiceImpl.java
  장우성.date/src/main/java/com/my/date/service/PlaceService.java
  장우성.date/src/main/java/com/my/date/service/PlaceServiceImpl.java
  장우성.date/src/main/java/com/my/date/service/ReviewService.java
  장우성.date/src/main/java/com/my/date/service/ReviewServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/CommentController.java
  장우성.date/src/main/java/com/my/date/web/PlaceController.java
  장우성.date/src/main/java/com/my/date/web/ReviewController.java
  장우성.date/src/main/resources/com/my/date/dao/map/commentMap.xml
  장우성.date/src/main/resources/com/my/date/dao/map/placeMap.xml
  장우성.date/src/main/resources/com/my/date/dao/map/reviewMap.xml
  장우성.date/src/main/webapp/WEB-INF/res/kakaoMap.css
  장우성.date/src/main/webapp/WEB-INF/res/mobile.css
  장우성.date/src/main/webapp/WEB-INF/view/place/place.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/list.jsp
Labels: ✨ Feature

#86 리뷰 상세 조회 및 삭제
  장우성.date/src/main/java/com/my/date/dao/ReviewDao.java
  장우성.date/src/main/java/com/my/date/dao/ReviewDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/ReviewMap.java
  장우성.date/src/main/java/com/my/date/service/ReviewService.java
  장우성.date/src/main/java/com/my/date/service/ReviewServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/ReviewController.java
  장우성.date/src/main/resources/com/my/date/dao/map/reviewMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/review/add.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/detailView.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/list.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/myReview.jsp
Labels: ✨ Feature

#89 관리자 장소 조회
  장우성.date/src/main/java/com/my/date/dao/PlaceDao.java
  장우성.date/src/main/java/com/my/date/dao/PlaceDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/PlaceMap.java
  장우성.date/src/main/java/com/my/date/domain/PlaceDetailDto.java
  장우성.date/src/main/java/com/my/date/service/PlaceService.java
  장우성.date/src/main/java/com/my/date/service/PlaceServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/placeMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/place.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/placeList.jsp
Labels: ✨ Feature

#91 장소리스트 조회
  장우성.date/src/main/java/com/my/date/dao/PlaceDao.java
  장우성.date/src/main/java/com/my/date/dao/PlaceDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/PlaceMap.java
  장우성.date/src/main/java/com/my/date/domain/PlaceDto.java
  장우성.date/src/main/java/com/my/date/service/PlaceService.java
  장우성.date/src/main/java/com/my/date/service/PlaceServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/java/com/my/date/web/PlaceController.java
  장우성.date/src/main/resources/com/my/date/dao/map/placeMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/main.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/list.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/place.jsp
Labels: ✨ Feature

#94 admin리뷰조회 장소명 검색 및 버그수정
  장우성.date/src/main/java/com/my/date/dao/ReviewDao.java
  장우성.date/src/main/java/com/my/date/dao/ReviewDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/ReviewMap.java
  장우성.date/src/main/java/com/my/date/service/ReviewService.java
  장우성.date/src/main/java/com/my/date/service/ReviewServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/webapp/WEB-INF/view/admin/review/reviewList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/detailView.jsp
Labels: 🐛 BugFix, ✨ Feature

#99 장소 신고 기능 구현
  장우성.date/src/main/java/com/my/date/dao/DeclarationDao.java
  장우성.date/src/main/java/com/my/date/dao/DeclarationDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/DeclarationMap.java
  장우성.date/src/main/java/com/my/date/service/DeclarationService.java
  장우성.date/src/main/java/com/my/date/service/DeclarationServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/DeclarationController.java
  장우성.date/src/main/resources/com/my/date/dao/map/declarationMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/review/reviewList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/declaration/add.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/place.jsp
Labels: ✨ Feature

#101 관리자 장소 추가
  장우성.date/src/main/java/com/my/date/AppConfig.java
  장우성.date/src/main/java/com/my/date/dao/PlaceDao.java
  장우성.date/src/main/java/com/my/date/dao/PlaceDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/RegionDao.java
  장우성.date/src/main/java/com/my/date/dao/RegionDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/PlaceMap.java
  장우성.date/src/main/java/com/my/date/dao/map/RegionMap.java
  장우성.date/src/main/java/com/my/date/service/PlaceService.java
  장우성.date/src/main/java/com/my/date/service/PlaceServiceImpl.java
  장우성.date/src/main/java/com/my/date/service/RegionService.java
  장우성.date/src/main/java/com/my/date/service/RegionServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/application.properties
  장우성.date/src/main/resources/com/my/date/dao/map/placeMap.xml
  장우성.date/src/main/resources/com/my/date/dao/map/regionMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/add.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/placeList.jsp
Labels: ✨ Feature

#105 Issue#48
  장우성.date/src/main/java/com/my/date/dao/DetailDao.java
  장우성.date/src/main/java/com/my/date/dao/DetailDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/DetailMap.java
  장우성.date/src/main/java/com/my/date/domain/Detail.java
  장우성.date/src/main/java/com/my/date/service/DetailService.java
  장우성.date/src/main/java/com/my/date/service/DetailServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/detailMap.xml
  장우성.date/src/main/resources/com/my/date/dao/map/placeMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/detail/patchDetail.jsp
Labels: ✨ Feature

#107 댓글 추가, 수정 기능
  장우성.date/src/main/java/com/my/date/dao/CommentDao.java
  장우성.date/src/main/java/com/my/date/dao/CommentDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/CommentMap.java
  장우성.date/src/main/java/com/my/date/service/CommentService.java
  장우성.date/src/main/java/com/my/date/service/CommentServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/CommentController.java
  장우성.date/src/main/resources/com/my/date/dao/map/commentMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/comment/fix.jsp
  장우성.date/src/main/webapp/WEB-INF/view/comment/listComment.jsp
Labels: ✨ Feature

#110 fix..
  장우성.date/src/main/java/com/my/date/service/CommentServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/CommentController.java
  장우성.date/src/main/webapp/WEB-INF/view/comment/fix.jsp
  장우성.date/src/main/webapp/WEB-INF/view/comment/listComment.jsp
Labels: 🐛 BugFix

#112 관리자메인
  장우성.date/src/main/java/com/my/date/dao/UserDao.java
  장우성.date/src/main/java/com/my/date/dao/UserDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/UserMap.java
  장우성.date/src/main/java/com/my/date/service/UserService.java
  장우성.date/src/main/java/com/my/date/service/UserServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/userMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/main.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/mypage.jsp
Labels: ✨ Feature

#114 아이디 저장
  장우성.date/src/main/java/com/my/date/web/UserController.java
  장우성.date/src/main/webapp/WEB-INF/view/user/login.jsp
Labels: ✨ Feature

#116 관심지역 추가/삭제
  장우성.date/src/main/java/com/my/date/dao/RegionDao.java
  장우성.date/src/main/java/com/my/date/dao/RegionDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/RegionMap.java
  장우성.date/src/main/java/com/my/date/service/RegionService.java
  장우성.date/src/main/java/com/my/date/service/RegionServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/RegionController.java
  장우성.date/src/main/resources/com/my/date/dao/map/regionMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/place/list.jsp
Labels: ✨ Feature

#117 issue#76
  장우성.date/src/main/java/com/my/date/dao/MenuDao.java
  장우성.date/src/main/java/com/my/date/dao/MenuDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/MenuMap.java
  장우성.date/src/main/java/com/my/date/service/MenuService.java
  장우성.date/src/main/java/com/my/date/service/MenuServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/menuMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/menu/patchMenu.jsp
Labels: ✨ Feature

#115 나의 피드 조회
  장우성.date/src/main/java/com/my/date/dao/FeedDao.java
  장우성.date/src/main/java/com/my/date/dao/FeedDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/FeedMap.java
  장우성.date/src/main/java/com/my/date/service/FeedService.java
  장우성.date/src/main/java/com/my/date/service/FeedServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/FeedController.java
  장우성.date/src/main/resources/com/my/date/dao/map/feedMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/community/addFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/community/listFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/community/myFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/declaration/add.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/mypage.jsp
Labels: ✨ Feature

#123 Issue#108
  장우성.date/src/main/java/com/my/date/dao/CommentDao.java
  장우성.date/src/main/java/com/my/date/dao/CommentDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/CommentMap.java
  장우성.date/src/main/java/com/my/date/service/CommentService.java
  장우성.date/src/main/java/com/my/date/service/CommentServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/CommentController.java
  장우성.date/src/main/resources/com/my/date/dao/map/commentMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/comment/fix.jsp
  장우성.date/src/main/webapp/WEB-INF/view/comment/listComment.jsp
Labels: ✨ Feature

#125 피드 수정
  장우성.date/src/main/java/com/my/date/dao/FeedDao.java
  장우성.date/src/main/java/com/my/date/dao/FeedDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/FeedMap.java
  장우성.date/src/main/java/com/my/date/service/FeedService.java
  장우성.date/src/main/java/com/my/date/service/FeedServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/FeedController.java
  장우성.date/src/main/resources/com/my/date/dao/map/feedMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/community/fixFeed.jsp
Labels: ✨ Feature

#127 fix.jsp 수정
  장우성.date/src/main/webapp/WEB-INF/view/comment/fix.jsp
Labels: 🐛 BugFix

#129 Issue#121
  .DS_Store
  장우성.date/.DS_Store
  장우성.date/src/main/java/com/my/date/dao/ReviewDao.java
  장우성.date/src/main/java/com/my/date/dao/ReviewDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/ReviewMap.java
  장우성.date/src/main/java/com/my/date/service/ReviewService.java
  장우성.date/src/main/java/com/my/date/service/ReviewServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/ReviewController.java
  장우성.date/src/main/resources/com/my/date/dao/map/reviewMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/review/reviewList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/add.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/detailView.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/list.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/myReview.jsp
Labels: ✨ Feature

#133 admin 리뷰 및 기타 버그 해결
  장우성.date/src/main/resources/com/my/date/dao/map/reviewMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/declaration/declareList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/main.jsp
Labels: 🔨 Refactor

#135 피드 삭제
  장우성.date/src/main/java/com/my/date/dao/FeedDao.java
  장우성.date/src/main/java/com/my/date/dao/FeedDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/FeedMap.java
  장우성.date/src/main/java/com/my/date/service/FeedService.java
  장우성.date/src/main/java/com/my/date/service/FeedServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/FeedController.java
  장우성.date/src/main/resources/com/my/date/dao/map/feedMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/community/detailFeed.jsp
Labels: ✨ Feature

#137 issue#119
  장우성.date/src/main/java/com/my/date/dao/MenuDao.java
  장우성.date/src/main/java/com/my/date/dao/MenuDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/MenuMap.java
  장우성.date/src/main/java/com/my/date/service/MenuService.java
  장우성.date/src/main/java/com/my/date/service/MenuServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/menuMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/menu/patchMenu.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/place.jsp
Labels: 🔨 Refactor

#139 아이디 저장 수정
  장우성.date/src/main/java/com/my/date/web/UserController.java
Labels: 🐛 BugFix

#141 Fix. 오류 수정, 피드 + Comment 병합
  장우성.date/src/main/java/com/my/date/dao/FeedDao.java
  장우성.date/src/main/java/com/my/date/dao/FeedDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/FeedMap.java
  장우성.date/src/main/java/com/my/date/domain/FeedDto.java
  장우성.date/src/main/java/com/my/date/service/FeedService.java
  장우성.date/src/main/java/com/my/date/service/FeedServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/java/com/my/date/web/CommentController.java
  장우성.date/src/main/java/com/my/date/web/FeedController.java
  장우성.date/src/main/resources/application.properties
  장우성.date/src/main/resources/com/my/date/dao/map/feedMap.xml
  장우성.date/src/main/resources/com/my/date/dao/map/placeMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/fix.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/place.jsp
  장우성.date/src/main/webapp/WEB-INF/view/comment/fix.jsp
  장우성.date/src/main/webapp/WEB-INF/view/comment/listComment.jsp
  장우성.date/src/main/webapp/WEB-INF/view/community/addFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/community/detailFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/community/listFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/place.jsp
Labels: 🐛 BugFix, 🔨 Refactor

#143 Issue#106
  장우성.date/src/main/java/com/my/date/dao/DetailDao.java
  장우성.date/src/main/java/com/my/date/dao/DetailDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/DetailMap.java
  장우성.date/src/main/java/com/my/date/service/DetailService.java
  장우성.date/src/main/java/com/my/date/service/DetailServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/resources/com/my/date/dao/map/detailMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/detail/addDetail.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/detail/patchDetail.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/place.jsp
Labels: ✨ Feature

#144 리뷰 리스트 url 수정
  장우성.date/src/main/webapp/WEB-INF/view/review/list.jsp
Labels: 🔨 Refactor

#146 BugFix
  장우성.date/src/main/java/com/my/date/Mkdir.java
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/webapp/WEB-INF/view/admin/declaration/declareList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/review/reviewList.jsp
Labels: 🐛 BugFix

#147 fix modal 수정
  장우성.date/src/main/webapp/WEB-INF/view/comment/fix.jsp
Labels: 🐛 BugFix

#149 price fix
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/place.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/place.jsp
Labels: 🐛 BugFix

#150 장소이름 및 카운트 기능
  장우성.date/src/main/java/com/my/date/web/AdminController.java
  장우성.date/src/main/webapp/WEB-INF/view/community/detailFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/place.jsp
Labels: 🐛 BugFix

#151 댓글 delete BugFix
  장우성.date/src/main/webapp/WEB-INF/view/community/detailFeed.jsp
Labels: 🐛 BugFix

#152 코드 수정
  장우성.date/src/main/resources/com/my/date/dao/map/reviewMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/review/reviewList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/main.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/list.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/place.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/detailView.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/list.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/myReview.jsp
Labels: 🐛 BugFix, 🔨 Refactor

#159 마이페이지 파일업로드
  장우성.date/src/main/java/com/my/date/dao/UserDao.java
  장우성.date/src/main/java/com/my/date/dao/UserDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/UserMap.java
  장우성.date/src/main/java/com/my/date/service/UserService.java
  장우성.date/src/main/java/com/my/date/service/UserServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/UserController.java
  장우성.date/src/main/resources/com/my/date/dao/map/userMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/user/mypage.jsp
Labels: ✨ Feature

#161 Update UserController.java
  장우성.date/src/main/java/com/my/date/web/UserController.java
Labels: 🐛 BugFix

#163 url 수정
  장우성.date/src/main/resources/com/my/date/dao/map/feedMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/admin/declaration/declareList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/detail/addDetail.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/detail/patchDetail.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/logo/logo.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/main.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/menu/patchMenu.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/add.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/fix.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/place.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/placeList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/review/reviewList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/admin/user/login.jsp
  장우성.date/src/main/webapp/WEB-INF/view/community/detailFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/community/myFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/place.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/detailView.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/list.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/myReview.jsp
Labels: 🔨 Refactor

#165 프로필사진 대체아이콘
  장우성.date/src/main/webapp/WEB-INF/view/user/mypage.jsp
Labels: ✨ Feature

#169 유저페이지 줄바꿈 수정
  장우성.date/src/main/webapp/WEB-INF/view/user/findId.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/findIdResult.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/findPassword.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/findPasswordResult.jsp
  장우성.date/src/main/webapp/WEB-INF/view/user/fixUser.jsp
Labels: 🐛 BugFix

#170 리뷰 프로필사진 수정
  장우성.date/src/main/webapp/WEB-INF/view/place/place.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/detailView.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/list.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/myReview.jsp
Labels: 🔨 Refactor

#172 추천장소 추가
  장우성.date/src/main/java/com/my/date/dao/PlaceDao.java
  장우성.date/src/main/java/com/my/date/dao/PlaceDaoImpl.java
  장우성.date/src/main/java/com/my/date/dao/map/PlaceMap.java
  장우성.date/src/main/java/com/my/date/domain/RecommendPlaceDto.java
  장우성.date/src/main/java/com/my/date/service/PlaceService.java
  장우성.date/src/main/java/com/my/date/service/PlaceServiceImpl.java
  장우성.date/src/main/java/com/my/date/web/PlaceController.java
  장우성.date/src/main/resources/com/my/date/dao/map/placeMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/main.jsp
Labels: ✨ Feature

#171 댓글 프로필 사진 fix
  장우성.date/src/main/java/com/my/date/domain/CommentDto.java
  장우성.date/src/main/java/com/my/date/web/CommentController.java
  장우성.date/src/main/resources/com/my/date/dao/map/commentMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/community/detailFeed.jsp
Labels: 🔨 Refactor

#174 메인 추천장소 사진크기수정
  장우성.date/src/main/webapp/WEB-INF/view/main.jsp
Labels: 🐛 BugFix

#176 fiximage
  장우성.date/src/main/webapp/WEB-INF/view/main.jsp
Labels: 🐛 BugFix

#179 placeList img size fix
  장우성.date/src/main/webapp/WEB-INF/view/main.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/list.jsp
Labels: 🔨 Refactor

#178 커뮤니티 업로드 모달x
  장우성.date/src/main/webapp/WEB-INF/view/community/addFeed.jsp
Labels: 🐛 BugFix

#180 장소추가null값수정
  장우성.date/src/main/webapp/WEB-INF/view/admin/detail/addDetail.jsp
Labels: 🐛 BugFix

#181 댓글 추가 null값 수정
  장우성.date/src/main/java/com/my/date/web/CommentController.java
  장우성.date/src/main/webapp/WEB-INF/view/community/detailFeed.jsp
Labels: 🔨 Refactor

#182 프로필 사진 사이즈 수정
  장우성.date/src/main/webapp/WEB-INF/view/place/place.jsp
Labels: 🔨 Refactor

#183 예외처리 모달
  장우성.date/src/main/webapp/WEB-INF/view/admin/place/add.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/list.jsp
  장우성.date/src/main/webapp/WEB-INF/view/review/add.jsp
Labels: 🔨 Refactor

#185 이미지수정
  장우성.date/src/main/webapp/WEB-INF/view/admin/review/reviewList.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/list.jsp
  장우성.date/src/main/webapp/WEB-INF/view/place/myPlace.jsp
Labels: 🔨 Refactor

#186 피드모달수정 리플토글제거
  장우성.date/src/main/webapp/WEB-INF/view/community/detailFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/community/fixFeed.jsp
Labels: 🐛 BugFix

#187 admin 로고 위치 수정
  장우성.date/src/main/webapp/WEB-INF/res/admin.css
  장우성.date/src/main/webapp/WEB-INF/view/admin/user/login.jsp
Labels: 🔨 Refactor

#188 프로필이미지 사이즈 수정
  장우성.date/src/main/resources/com/my/date/dao/map/feedMap.xml
  장우성.date/src/main/webapp/WEB-INF/view/community/listFeed.jsp
  장우성.date/src/main/webapp/WEB-INF/view/community/myFeed.jsp
Labels: 🔨 Refactor
